apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Audit PostgreSQL
    uid: audit-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: dag_audit
    user: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: postgres
    editable: true
